# Generated by Django 5.2.4 on 2026-01-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='owner',
        ),
    ]
